# Generated by Django 5.0.4 on 2024-04-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignDelBoys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignkey', models.CharField(max_length=8)),
                ('cartid', models.CharField(max_length=11)),
                ('loginid', models.IntegerField()),
                ('currentdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.CharField(max_length=15)),
                ('holdername', models.CharField(max_length=20)),
                ('bankname', models.CharField(max_length=20)),
                ('branchname', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=11)),
                ('cardno', models.CharField(max_length=12)),
                ('cvv', models.IntegerField()),
                ('edate', models.DateField()),
                ('tamount', models.CharField(max_length=7)),
                ('contactno', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartkey', models.CharField(max_length=8)),
                ('loginid', models.IntegerField()),
                ('menuid', models.IntegerField()),
                ('currentdate', models.DateField()),
                ('quantity', models.IntegerField()),
                ('totalamount', models.IntegerField()),
                ('paymentstatus', models.IntegerField()),
                ('delstatus', models.IntegerField()),
                ('returnstatus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compkey', models.CharField(max_length=8)),
                ('complaint', models.CharField(max_length=60)),
                ('productid', models.IntegerField()),
                ('loginid', models.IntegerField()),
                ('currentdate', models.DateField()),
                ('adreply', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckey', models.CharField(max_length=8)),
                ('customername', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=60)),
                ('contact', models.CharField(max_length=12)),
                ('loginid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delkey', models.CharField(max_length=8)),
                ('delname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=60)),
                ('pincode', models.CharField(max_length=6)),
                ('district', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('contactno', models.CharField(max_length=12)),
                ('loginid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedkey', models.CharField(max_length=8)),
                ('feedback', models.CharField(max_length=60)),
                ('productid', models.IntegerField()),
                ('loginid', models.IntegerField()),
                ('currentdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lkey', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=1)),
                ('usertype', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offkey', models.CharField(max_length=8)),
                ('productid', models.IntegerField()),
                ('offers', models.CharField(max_length=60)),
                ('loginid', models.IntegerField()),
                ('currentdate', models.DateField()),
                ('offerlimit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pykey', models.CharField(max_length=8)),
                ('cowner', models.CharField(max_length=20)),
                ('card', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('edate', models.DateField()),
                ('loginid', models.IntegerField()),
                ('cdate', models.DateField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productkey', models.CharField(max_length=8)),
                ('category', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('image', models.TextField()),
                ('details', models.CharField(max_length=60)),
                ('rentamt', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('loginid', models.IntegerField()),
                ('selling', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returnkey', models.CharField(max_length=8)),
                ('reason', models.CharField(max_length=60)),
                ('cartid', models.IntegerField()),
                ('loginid', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RentDtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentkey', models.CharField(max_length=8)),
                ('days', models.IntegerField()),
                ('address', models.CharField(max_length=60)),
                ('quantity', models.IntegerField()),
                ('productid', models.IntegerField()),
                ('currentdate', models.DateField()),
                ('loginid', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventkey', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=20)),
                ('image', models.TextField()),
                ('address', models.CharField(max_length=60)),
                ('pincode', models.CharField(max_length=6)),
                ('dist', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=12)),
                ('registration', models.IntegerField()),
                ('loginid', models.IntegerField()),
            ],
        ),
    ]
