# Generated by Django 5.0.4 on 2024-04-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_assigndelboys_assignkey_remove_cart_cartkey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='loginid',
        ),
        migrations.RemoveField(
            model_name='deliveryboy',
            name='loginid',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='loginid',
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(upload_to='shop_images/'),
        ),
    ]
