# Generated by Django 5.0.4 on 2024-04-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_customer_loginid_remove_deliveryboy_loginid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
