# Generated by Django 5.0.4 on 2024-04-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_shop_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='usertype',
        ),
        migrations.AddField(
            model_name='shop',
            name='approvalstatus',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
    ]
