# Generated by Django 5.0.4 on 2024-04-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_shop_usertype_shop_approvalstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='usertype',
        ),
        migrations.RemoveField(
            model_name='deliveryboy',
            name='usertype',
        ),
    ]
