# Generated by Django 5.0.4 on 2024-04-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='myapp/images/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(upload_to='myapp/images/'),
        ),
    ]
