# Generated by Django 5.0.4 on 2024-04-09 08:04

import django.core.validators
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_customer_address_alter_customer_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customername',
            field=models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20), myapp.models.validate_no_numbers]),
        ),
    ]
