# Generated by Django 5.0.4 on 2024-04-21 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_customer_customername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='assigndelboys',
            name='currentdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='adreply',
            field=models.CharField(max_length=60, validators=[django.core.validators.MaxLengthValidator(60)]),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='complaint',
            field=models.CharField(max_length=60, validators=[django.core.validators.MaxLengthValidator(60)]),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='currentdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='loginid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='productid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='currentdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(max_length=60, validators=[django.core.validators.MaxLengthValidator(60)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='loginid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='productid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offers',
            field=models.CharField(max_length=60, validators=[django.core.validators.MaxLengthValidator(60)]),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
